CREATE TABLE pjdke.flow (
  id     INTEGER UNSIGNED NOT NULL,
  prev   VARCHAR(255),
  cur    VARCHAR(255)     NOT NULL,
  next   VARCHAR(255),
  tsPrev TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  tsCur  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  tsNext TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)